name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DigitalOcean Container Registry
      run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login ${{ secrets.DIGITALOCEAN_REGISTRY }} -u "do-access-token" --password-stdin

    - name: Build and push Docker image to DigitalOcean
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DIGITALOCEAN_REGISTRY }}/envvartest:latest
